// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsAFIJLq3QUhzg_NP47CRe37vYugcay94',
    appId: '1:507741712862:web:75a391a85de6776296ed4f',
    messagingSenderId: '507741712862',
    projectId: 'darvesh-classes-ac86c',
    authDomain: 'darvesh-classes-ac86c.firebaseapp.com',
    databaseURL: 'https://darvesh-classes-ac86c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'darvesh-classes-ac86c.appspot.com',
    measurementId: 'G-VWQY932QWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClpknc5ptj_4M9DabbaFsupRmbO6e3l2I',
    appId: '1:507741712862:android:71683e1887702f5d96ed4f',
    messagingSenderId: '507741712862',
    projectId: 'darvesh-classes-ac86c',
    databaseURL: 'https://darvesh-classes-ac86c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'darvesh-classes-ac86c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrktmNRcD2_-0i8lBPJmrT63aoWwq7njo',
    appId: '1:507741712862:ios:df5270d6fd47b66b96ed4f',
    messagingSenderId: '507741712862',
    projectId: 'darvesh-classes-ac86c',
    databaseURL: 'https://darvesh-classes-ac86c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'darvesh-classes-ac86c.appspot.com',
    androidClientId: '507741712862-gopqfcema603b9cv0bmmgucsoq7rb3pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.darveshClasses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrktmNRcD2_-0i8lBPJmrT63aoWwq7njo',
    appId: '1:507741712862:ios:df5270d6fd47b66b96ed4f',
    messagingSenderId: '507741712862',
    projectId: 'darvesh-classes-ac86c',
    databaseURL: 'https://darvesh-classes-ac86c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'darvesh-classes-ac86c.appspot.com',
    androidClientId: '507741712862-gopqfcema603b9cv0bmmgucsoq7rb3pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.darveshClasses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsAFIJLq3QUhzg_NP47CRe37vYugcay94',
    appId: '1:507741712862:web:5218d8313222cd4a96ed4f',
    messagingSenderId: '507741712862',
    projectId: 'darvesh-classes-ac86c',
    authDomain: 'darvesh-classes-ac86c.firebaseapp.com',
    databaseURL: 'https://darvesh-classes-ac86c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'darvesh-classes-ac86c.appspot.com',
    measurementId: 'G-30L4K96YN1',
  );
}
